(function(){
'use strict';
const KEY='sb_publishable_GF2VPswgkkieqYs1SCj1Hg_Fmxz0dPj';
const API='/supa';
const $=s=>document.querySelector(s);
function token(){return localStorage.getItem('aich_access_token')||''}
function h(){return {'apikey':KEY,'Authorization':'Bearer '+token(),'Content-Type':'application/json'}}
async function req(path,opt={}){opt.headers=Object.assign(h(),opt.headers||{});return fetch(API+path,opt)}
function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function shortId(v){v=String(v||'');return v.length>12?v.slice(0,8)+'…':v}
function statusLabel(s){return ({pending:'대기',approved:'승인',rejected:'반려',fulfilled:'지급완료'})[s]||s}
async function isAdmin(){if(!token())return false;try{const u=await req('/auth/v1/user');if(!u.ok)return false;const user=await u.json();const r=await req('/rest/v1/profiles?id=eq.'+encodeURIComponent(user.id)+'&select=role&limit=1');if(!r.ok)return false;const rows=await r.json();return rows[0]&&rows[0].role==='admin'}catch(_){return false}}
async function signedProof(path){if(!path)return null;try{const r=await fetch(API+'/storage/v1/object/sign/award-proofs/'+encodeURI(path),{method:'POST',headers:h(),body:JSON.stringify({expiresIn:600})});if(!r.ok)return null;const d=await r.json();return d.signedURL?API+'/storage/v1'+d.signedURL:null}catch(_){return null}}
async function loadAdmin(){const box=$('#adminRewards');if(!box)return;if(!(await isAdmin())){box.hidden=true;return}box.hidden=false;await Promise.all([loadAwards(),loadClaims()])}
async function loadAwards(){const list=$('#adminAwardList');if(!list)return;list.innerHTML='<div class="adminEmpty">불러오는 중…</div>';const r=await req('/rest/v1/award_verifications?status=eq.pending&select=id,user_id,contest_title,award_name,proof_url,status,submitted_at&order=submitted_at.asc&limit=100');if(!r.ok){list.innerHTML='<div class="adminEmpty">수상 인증을 불러오지 못했습니다.</div>';return}const rows=await r.json();$('#pendingAwardCount').textContent=rows.length;if(!rows.length){list.innerHTML='<div class="adminEmpty">검토 대기 중인 인증이 없습니다.</div>';return}list.innerHTML=rows.map(x=>`<article class="adminReview" data-award="${esc(x.id)}"><div class="adminReviewTop"><div><small>${esc(new Date(x.submitted_at).toLocaleString('ko-KR'))}</small><b>${esc(x.contest_title)}</b><span>🏆 ${esc(x.award_name)}</span></div><em>${esc(shortId(x.user_id))}</em></div><div class="adminActions"><button data-proof="${esc(x.proof_url||'')}">증빙 보기</button><button class="reject" data-award-status="rejected">반려</button><button class="approve" data-award-status="approved">승인</button></div></article>`).join('');list.querySelectorAll('[data-proof]').forEach(b=>b.onclick=async()=>{b.disabled=true;const url=await signedProof(b.dataset.proof);b.disabled=false;if(url)window.open(url,'_blank','noopener');else alert('증빙 파일 링크를 만들지 못했습니다.')});list.querySelectorAll('[data-award-status]').forEach(b=>b.onclick=()=>updateAward(b.closest('[data-award]').dataset.award,b.dataset.awardStatus))}
async function updateAward(id,status){if(!confirm(status==='approved'?'이 수상 인증을 승인할까요?':'이 수상 인증을 반려할까요?'))return;const r=await req('/rest/v1/award_verifications?id=eq.'+encodeURIComponent(id),{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({status,reviewed_at:new Date().toISOString()})});if(!r.ok){alert('처리하지 못했습니다.');return}await Promise.all([loadAwards(),loadClaims()])}
async function loadClaims(){const list=$('#adminRewardList');if(!list)return;list.innerHTML='<div class="adminEmpty">불러오는 중…</div>';const r=await req('/rest/v1/reward_claims?status=eq.pending&select=id,user_id,reward_type,source_ref,status,created_at&order=created_at.asc&limit=100');if(!r.ok){list.innerHTML='<div class="adminEmpty">리워드 신청을 불러오지 못했습니다.</div>';return}const rows=await r.json();$('#pendingRewardCount').textContent=rows.length;if(!rows.length){list.innerHTML='<div class="adminEmpty">지급 대기 중인 리워드가 없습니다.</div>';return}list.innerHTML=rows.map(x=>`<article class="adminReview" data-claim="${esc(x.id)}"><div class="adminReviewTop"><div><small>${esc(new Date(x.created_at).toLocaleString('ko-KR'))}</small><b>${x.reward_type==='monthly_coffee'?'☕ 월간 커피 리워드':'🎁 수상 인증 리워드'}</b><span>${esc(x.source_ref||'')}</span></div><em>${esc(shortId(x.user_id))}</em></div><div class="adminActions"><button class="reject" data-claim-status="rejected">지급 제외</button><button class="approve" data-claim-status="fulfilled">지급 완료</button></div></article>`).join('');list.querySelectorAll('[data-claim-status]').forEach(b=>b.onclick=()=>updateClaim(b.closest('[data-claim]').dataset.claim,b.dataset.claimStatus))}
async function updateClaim(id,status){if(!confirm(status==='fulfilled'?'쿠폰/리워드 지급 완료로 처리할까요?':'이 리워드 신청을 제외할까요?'))return;const body={status};if(status==='fulfilled')body.fulfilled_at=new Date().toISOString();const r=await req('/rest/v1/reward_claims?id=eq.'+encodeURIComponent(id),{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify(body)});if(!r.ok){alert('처리하지 못했습니다.');return}await loadClaims()}
function boot(){let tries=0;const timer=setInterval(async()=>{tries++;if(token()){clearInterval(timer);await loadAdmin()}else if(tries>30)clearInterval(timer)},500);const refresh=$('#adminRefresh');if(refresh)refresh.onclick=loadAdmin;document.addEventListener('visibilitychange',()=>{if(!document.hidden&&token())loadAdmin()})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();