const SUPABASE_URL='https://odnvwjsggafgljheqhlo.supabase.co';
const SUPABASE_KEY='';
const CATEGORIES=['전체','AI 영상','AI 이미지','AI 글쓰기','AI 영화','AI 교육','AI 정책'];
let contests=[],activeCategory='전체',saved=new Set(JSON.parse(localStorage.getItem('aich_saved')||'[]'));
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function pick(o,...ks){for(const k of ks)if(o?.[k]!==undefined&&o[k]!==null&&o[k]!=='')return o[k];return ''}
function normalize(x){const p=x.parsed_data||{};return {id:String(pick(x,'id','source_url')||Math.random()),title:pick(x,'title', 'title_ko')||pick(p,'title_ko','title_original','title')||'AI Opportunity',host:pick(x,'host','organizer')||pick(p,'host','organizer')||'',deadline:pick(x,'deadline','deadline_at','end_date')||pick(p,'deadline','deadline_at')||'',image:pick(x,'image_url','poster_url','thumbnail_url','imageUrl','thumbnailUrl')||pick(p,'image_url','poster_url','thumbnail_url','imageUrl')||'',url:pick(x,'application_url','source_url','url')||pick(p,'application_url','source_url','url')||'#',country:pick(x,'country')||pick(p,'country')||'',summary:pick(x,'summary_ko','summary','description')||pick(p,'summary_ko','summary','description')||'',ai:pick(x,'ai_policy','ai_usage')||pick(p,'ai_policy','ai_usage')||'unclear',category:categorize(x,p),global:Boolean(pick(x,'is_global')||pick(p,'is_global'))};}
function categorize(x,p){const explicit=String(pick(x,'category','opportunity_category')||pick(p,'category','opportunity_category')||'').toLowerCase();const t=(pick(x,'title','summary_ko','description')+' '+pick(p,'title_ko','title_original','summary_ko','tags')).toLowerCase();if(/영화|film|cinema|festival/.test(explicit+' '+t))return 'AI 영화';if(/교육|education|course|academy|training|fellowship/.test(explicit+' '+t))return 'AI 교육';if(/정책|policy|공공데이터|governance|regulation/.test(explicit+' '+t))return 'AI 정책';if(/글|writing|writer|essay|소설|시나리오|script/.test(explicit+' '+t))return 'AI 글쓰기';if(/이미지|image|photo|사진|art|design|illustration/.test(explicit+' '+t))return 'AI 이미지';return 'AI 영상'}
function days(d){if(!d)return null;const dt=new Date(d);if(isNaN(dt))return null;return Math.ceil((dt-new Date())/86400000)}
function dLabel(d){const n=days(d);if(n===null)return 'OPEN';if(n===0)return 'D-DAY';if(n<0)return '마감';return `D-${n}`}
function aiLabel(v){v=String(v).toLowerCase();if(v.includes('required')||v.includes('필수'))return 'AI 필수';if(v.includes('allowed')||v.includes('가능'))return 'AI 사용 가능';if(v.includes('limited')||v.includes('일부'))return 'AI 일부 허용';return 'AI 확인필요'}
function card(c){const n=days(c.deadline),urgent=n!==null&&n>=0&&n<=7,today=n===0;return `<article class="card" data-id="${esc(c.id)}"><div class="poster">${c.image?`<img src="${esc(c.image)}" loading="lazy" referrerpolicy="no-referrer" onerror="this.outerHTML='<div class=\'fallback\'><div><b>AI</b>Official opportunity</div></div>'">`:`<div class="fallback"><div><b>AI</b>${esc(c.category)}</div></div>`}<div class="badges"><span class="badge ai">${aiLabel(c.ai)}</span><span class="badge category">${esc(c.category)}</span>${c.global?'<span class="badge global">🌎 GLOBAL</span>':''}</div><span class="dday ${urgent?'urgent':''} ${today?'today':''}">${dLabel(c.deadline)}</span></div><div class="cardBody"><span class="deadline">${esc(String(c.deadline||'상시 모집').slice(0,16))}</span><h3>${esc(c.title)}</h3><div class="host">${esc(c.host||c.country||'Official organizer')}</div></div><button class="save ${saved.has(c.id)?'on':''}" data-save="${esc(c.id)}">${saved.has(c.id)?'♥':'♡'}</button></article>`}
function categories(){for(const id of ['homeCategories','exploreCategories']){const e=document.getElementById(id);e.innerHTML=CATEGORIES.map(c=>`<button class="cat ${c===activeCategory?'on':''}" data-cat="${c}">${c}</button>`).join('')}}
function filtered(){const q=($('#q')?.value||$('#homeQ')?.value||'').trim().toLowerCase(),ai=$('#aiFilter')?.value||'all',scope=$('#scopeFilter')?.value||'all';return contests.filter(c=>{const text=(c.title+' '+c.host+' '+c.summary+' '+c.category).toLowerCase();if(q&&!text.includes(q))return false;if(activeCategory!=='전체'&&c.category!==activeCategory)return false;if(ai==='ready'&&aiLabel(c.ai)==='AI 확인필요')return false;if(ai!=='all'&&ai!=='ready'&&!String(c.ai).toLowerCase().includes(ai))return false;if(scope==='global'&&!c.global)return false;if(scope==='korea'&&!/korea|대한민국|한국|kr/i.test(c.country+' '+c.host))return false;if(scope==='overseas'&&/korea|대한민국|한국|kr/i.test(c.country+' '+c.host))return false;return true})}
function render(){categories();const f=filtered().filter(c=>{const n=days(c.deadline);return n===null||n>=0});$('#resultCount').textContent=f.length;$('#all').innerHTML=f.length?f.map(card).join(''):'<div class="empty"><b>조건에 맞는 기회가 없습니다.</b>다른 카테고리나 검색어를 선택해 보세요.</div>';const open=contests.filter(c=>days(c.deadline)===null||days(c.deadline)>=0);$('#globalPicks').innerHTML=open.slice(0,4).map(card).join('');$('#deadlineGrid').innerHTML=open.filter(c=>days(c.deadline)!==null).sort((a,b)=>days(a.deadline)-days(b.deadline)).slice(0,4).map(card).join('');$('#latest').innerHTML=open.slice(-4).reverse().map(card).join('');const sv=contests.filter(c=>saved.has(c.id));$('#savedGrid').innerHTML=sv.length?sv.map(card).join(''):'<div class="empty"><b>아직 저장한 기회가 없습니다.</b>♡ 버튼을 눌러 관심 기회를 저장하세요.</div>';bindCards()}
function bindCards(){$$('[data-save]').forEach(b=>b.onclick=e=>{e.stopPropagation();const id=b.dataset.save;saved.has(id)?saved.delete(id):saved.add(id);localStorage.setItem('aich_saved',JSON.stringify([...saved]));render()});$$('.card').forEach(el=>el.onclick=()=>showDetail(contests.find(c=>c.id===el.dataset.id)))}
function showDetail(c){if(!c)return;$('#detailBody').innerHTML=`${c.image?`<img class="detailPoster" src="${esc(c.image)}" referrerpolicy="no-referrer">`:''}<p><span class="badge ai">${aiLabel(c.ai)}</span> <span class="badge category">${esc(c.category)}</span></p><h2 class="detailTitle">${esc(c.title)}</h2><div class="detailBlock"><small>주최</small>${esc(c.host||'-')}</div><div class="detailBlock"><small>마감</small>${esc(c.deadline||'상시 모집')} · <b style="color:var(--pink2)">${dLabel(c.deadline)}</b></div><div class="detailBlock"><small>AI Contest Hub 요약</small>${esc(c.summary||'공식 모집요강을 확인해 주세요.')}</div><div class="detailBlock"><small>AI 사용 정책</small>${aiLabel(c.ai)}</div><a class="apply" href="${esc(c.url)}" target="_blank" rel="noopener">공식 페이지에서 지원하기 ↗</a>`;$('#detailModal').classList.add('open')}
function go(id){$$('.screen').forEach(x=>x.classList.toggle('active',x.id===id));$$('.nav button').forEach(x=>x.classList.toggle('on',x.dataset.go===id));scrollTo(0,0);if(id==='explore')render()}
async function load(){try{const url=`${SUPABASE_URL}/rest/v1/contests?select=*&order=created_at.desc&limit=500`;const h={'apikey':SUPABASE_KEY,'Authorization':`Bearer ${SUPABASE_KEY}`};if(!SUPABASE_KEY)throw new Error('Supabase public key required');const r=await fetch(url,{headers:h});if(!r.ok)throw new Error('DB '+r.status);contests=(await r.json()).map(normalize);$('#cloudState').textContent=`LIVE · ${contests.length} Opportunities`;render()}catch(e){$('#cloudState').textContent='DB 연결 설정 필요';contests=[];render();console.warn(e)}}
$$('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));$('#searchTop').onclick=()=>go('explore');$('#homeSearch').onclick=e=>{if(e.target.tagName!=='INPUT')go('explore')};$('#homeQ').addEventListener('focus',()=>go('explore'));$('#q').addEventListener('input',render);$('#aiFilter').addEventListener('change',render);$('#scopeFilter').addEventListener('change',render);document.addEventListener('click',e=>{const b=e.target.closest('[data-cat]');if(b){activeCategory=b.dataset.cat;if($('#homeQ').value)$('#q').value=$('#homeQ').value;render()}});$('[data-deadline]').onclick=()=>{go('explore');$('#q').value='';render()};$('#detailClose').onclick=()=>$('#detailModal').classList.remove('open');$('#detailModal').onclick=e=>{if(e.target.id==='detailModal')e.currentTarget.classList.remove('open')};
load();