(function(){
'use strict';
const KEY='sb_publishable_GF2VPswgkkieqYs1SCj1Hg_Fmxz0dPj';
const API='/supa';
const CATEGORIES=['전체','AI 영상','AI 이미지','AI 글쓰기','AI 영화','AI 교육','AI 정책'];
let contests=[],activeCategory='전체',currentUser=null;
let saved=new Set(JSON.parse(localStorage.getItem('aich_saved')||'[]'));
let monthCheckins=0;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function pick(o,...ks){for(const k of ks)if(o?.[k]!==undefined&&o[k]!==null&&o[k]!=='')return o[k];return ''}
function token(){return localStorage.getItem('aich_access_token')||''}
function headers(auth=true){const h={'apikey':KEY,'Content-Type':'application/json'};if(auth&&token())h.Authorization='Bearer '+token();return h}
function req(path,opt={}){opt.headers=Object.assign(headers(opt.auth!==false),opt.headers||{});return fetch(API+path,opt)}
function normalize(x){const p=x.parsed_data||{};return {id:String(pick(x,'id','source_url')||Math.random()),title:pick(x,'title_ko','title','title_original')||pick(p,'title_ko','title_original','title')||'AI Opportunity',host:pick(x,'host','organizer')||pick(p,'host','organizer')||'',deadline:pick(x,'deadline_at','deadline','end_date')||pick(p,'deadline_at','deadline')||'',image:pick(x,'poster_url','thumbnail_url','banner_url','image_url','imageUrl','thumbnailUrl')||pick(p,'poster_url','thumbnail_url','image_url','imageUrl')||'',url:pick(x,'application_url','source_url','url')||pick(p,'application_url','source_url','url')||'#',source:pick(x,'source_url')||pick(p,'source_url')||'',country:pick(x,'country','country_code','region')||pick(p,'country','country_code')||'',summary:pick(x,'summary_ko','summary','description')||pick(p,'summary_ko','summary','description')||'',ai:pick(x,'ai_badge','ai_policy','ai_usage')||pick(p,'ai_policy','ai_usage')||'unclear',category:categorize(x,p),global:Boolean(pick(x,'is_global')||pick(p,'is_global')),created:pick(x,'created_at')||'',eligibility:pick(x,'eligibility')||pick(p,'eligibility')||'',benefit:pick(x,'benefit','prize')||pick(p,'benefit','prize')||''}}
function categorize(x,p){const direct=pick(x,'primary_ai_category')||pick(p,'primary_ai_category');if(CATEGORIES.includes(direct))return direct;const explicit=String(pick(x,'category','opportunity_category')||pick(p,'category','opportunity_category')||'').toLowerCase();const tags=Array.isArray(x.tags)?x.tags.join(' '):String(x.tags||'');const t=(pick(x,'title','title_ko','summary_ko','description')+' '+pick(p,'title_ko','title_original','summary_ko')+' '+tags).toLowerCase();if(/영화|film|cinema|드라마|trailer/.test(explicit+' '+t))return 'AI 영화';if(/교육|education|course|academy|training|fellowship|과정|캠퍼스/.test(explicit+' '+t))return 'AI 교육';if(/글|writing|writer|essay|소설|대본|script|논문/.test(explicit+' '+t))return 'AI 글쓰기';if(/이미지|image|photo|사진|illustration|세밀화|디자인|design/.test(explicit+' '+t))return 'AI 이미지';if(/영상|video|short|숏폼|광고|콘텐츠|media/.test(explicit+' '+t))return 'AI 영상';return 'AI 정책'}
function days(d){if(!d)return null;const dt=new Date(d);if(isNaN(dt))return null;return Math.ceil((dt-new Date())/86400000)}
function dLabel(d){const n=days(d);if(n===null)return 'OPEN';if(n===0)return 'D-DAY';if(n<0)return '마감';return `D-${n}`}
function deadlineText(v){if(!v)return '상시 모집';try{const d=new Date(v);if(isNaN(d))return String(v).slice(0,16);return new Intl.DateTimeFormat('ko-KR',{year:'numeric',month:'2-digit',day:'2-digit'}).format(d)}catch(_){return String(v).slice(0,16)}}
function aiLabel(v){v=String(v).toLowerCase();if(v.includes('필수')||v.includes('required'))return 'AI 필수';if(v.includes('사용 가능')||v.includes('allowed')||v==='가능')return 'AI 사용 가능';if(v.includes('일부')||v.includes('limited'))return 'AI 일부 허용';if(v.includes('불가')||v.includes('prohibited'))return 'AI 사용 불가';return 'AI 규정 확인필요'}
function aiClass(v){const l=aiLabel(v);return l==='AI 규정 확인필요'||l==='AI 사용 불가'?'':'ai'}
function card(c){const n=days(c.deadline),urgent=n!==null&&n>=0&&n<=7,today=n===0;const img=c.image&&c.image!=='#';return `<article class="card" data-id="${esc(c.id)}"><div class="poster"><div class="fallback"><div><b>AI</b>${esc(c.category)}</div></div>${img?`<img src="${esc(c.image)}" loading="lazy" referrerpolicy="no-referrer" onerror="this.style.display='none'">`:''}<div class="badges"><span class="badge ${aiClass(c.ai)}">${aiLabel(c.ai)}</span><span class="badge category">${esc(c.category)}</span>${c.global?'<span class="badge global">🌎 GLOBAL</span>':''}</div><span class="dday ${urgent?'urgent':''} ${today?'today':''}">${dLabel(c.deadline)}</span></div><div class="cardBody"><span class="deadline">${esc(deadlineText(c.deadline))}</span><h3>${esc(c.title)}</h3><div class="host">${esc(c.host||c.country||'Official organizer')}</div></div><button class="save ${saved.has(c.id)?'on':''}" data-save="${esc(c.id)}">${saved.has(c.id)?'♥':'♡'}</button></article>`}
function categories(){for(const id of ['homeCategories','exploreCategories']){const e=document.getElementById(id);if(e)e.innerHTML=CATEGORIES.map(c=>`<button class="cat ${c===activeCategory?'on':''}" data-cat="${c}">${c}</button>`).join('')}}
function isKorea(c){return /korea|대한민국|한국|south korea|\bkr\b/i.test((c.country||'')+' '+(c.host||''))}
function openItems(){return contests.filter(c=>aiLabel(c.ai)!=='AI 사용 불가'&&(days(c.deadline)===null||days(c.deadline)>=0))}
function filtered(){const q=($('#q')?.value||'').trim().toLowerCase(),ai=$('#aiFilter')?.value||'all',scope=$('#scopeFilter')?.value||'all';return openItems().filter(c=>{const text=(c.title+' '+c.host+' '+c.summary+' '+c.category+' '+c.country).toLowerCase();if(q&&!text.includes(q))return false;if(activeCategory!=='전체'&&c.category!==activeCategory)return false;const label=aiLabel(c.ai);if(ai==='ready'&&!['AI 필수','AI 사용 가능','AI 일부 허용'].includes(label))return false;if(ai==='required'&&label!=='AI 필수')return false;if(ai==='allowed'&&label!=='AI 사용 가능')return false;if(ai==='limited'&&label!=='AI 일부 허용')return false;if(ai==='unclear'&&label!=='AI 규정 확인필요')return false;if(scope==='global'&&!c.global)return false;if(scope==='korea'&&!isKorea(c))return false;if(scope==='overseas'&&(isKorea(c)&&!c.global))return false;return true})}
function render(){categories();const f=filtered();if($('#resultCount'))$('#resultCount').textContent=f.length;if($('#all'))$('#all').innerHTML=f.length?f.map(card).join(''):'<div class="empty"><b>조건에 맞는 기회가 없습니다.</b>다른 카테고리나 검색어를 선택해 보세요.</div>';const open=openItems();const picks=open.slice().sort((a,b)=>(b.global-a.global)||(days(a.deadline)??9999)-(days(b.deadline)??9999)).slice(0,4);if($('#globalPicks'))$('#globalPicks').innerHTML=picks.map(card).join('');if($('#deadlineGrid'))$('#deadlineGrid').innerHTML=open.filter(c=>days(c.deadline)!==null).sort((a,b)=>days(a.deadline)-days(b.deadline)).slice(0,4).map(card).join('');if($('#latest'))$('#latest').innerHTML=open.slice().sort((a,b)=>new Date(b.created||0)-new Date(a.created||0)).slice(0,4).map(card).join('');if($('#savedGrid')){const sv=contests.filter(c=>saved.has(c.id));$('#savedGrid').innerHTML=sv.length?sv.map(card).join(''):'<div class="empty"><b>아직 저장한 기회가 없습니다.</b>♡ 버튼을 눌러 관심 기회를 저장하세요.</div>'}bindCards()}
function bindCards(){$$('[data-save]').forEach(b=>b.onclick=e=>{e.stopPropagation();toggleSave(b.dataset.save)});$$('.card').forEach(el=>el.onclick=()=>showDetail(contests.find(c=>c.id===el.dataset.id)))}
async function toggleSave(id){saved.has(id)?saved.delete(id):saved.add(id);localStorage.setItem('aich_saved',JSON.stringify([...saved]));render();if(currentUser){try{if(saved.has(id))await req('/rest/v1/saved_contests?on_conflict=user_id,contest_id',{method:'POST',headers:{Prefer:'resolution=merge-duplicates'},body:JSON.stringify({user_id:currentUser.id,contest_id:id})});else await req('/rest/v1/saved_contests?user_id=eq.'+encodeURIComponent(currentUser.id)+'&contest_id=eq.'+encodeURIComponent(id),{method:'DELETE'})}catch(_){}}}
function showDetail(c){if(!c)return;$('#detailBody').innerHTML=`${c.image?`<img class="detailPoster" src="${esc(c.image)}" referrerpolicy="no-referrer">`:''}<p><span class="badge ${aiClass(c.ai)}">${aiLabel(c.ai)}</span> <span class="badge category">${esc(c.category)}</span></p><h2 class="detailTitle">${esc(c.title)}</h2><div class="detailBlock"><small>주최</small>${esc(c.host||'-')}</div><div class="detailBlock"><small>마감</small>${esc(deadlineText(c.deadline))} · <b style="color:var(--pink2)">${dLabel(c.deadline)}</b></div><div class="detailBlock"><small>AI Contest Hub 요약</small>${esc(c.summary||'공식 모집요강을 확인해 주세요.')}</div><div class="detailBlock"><small>AI 사용 정책</small>${aiLabel(c.ai)}</div>${c.eligibility?`<div class="detailBlock"><small>참가 자격</small>${esc(c.eligibility)}</div>`:''}${c.benefit?`<div class="detailBlock"><small>상금·혜택</small>${esc(c.benefit)}</div>`:''}${c.url&&c.url!=='#'?`<a class="apply" href="${esc(c.url)}" target="_blank" rel="noopener">공식 페이지에서 지원하기 ↗</a>`:''}`;$('#detailModal').classList.add('open')}
function go(id){$$('.screen').forEach(x=>x.classList.toggle('active',x.id===id));$$('.nav button').forEach(x=>x.classList.toggle('on',x.dataset.go===id));scrollTo(0,0);if(id==='explore'||id==='saved')render();if(id==='my'&&currentUser)loadRewards()}
async function load(){try{const r=await req('/rest/v1/contests?status=eq.live&select=*&order=display_order.asc,deadline.asc&limit=500',{auth:false});if(!r.ok)throw new Error('DB '+r.status);contests=(await r.json()).map(normalize);$('#cloudState').textContent=`LIVE · ${contests.length} Opportunities`;render()}catch(e){$('#cloudState').textContent='DB 연결 실패';contests=[];render();console.warn(e)}}
async function current(){if(!token())return;try{const r=await req('/auth/v1/user');if(!r.ok){localStorage.removeItem('aich_access_token');return}currentUser=await r.json();$('#name').textContent=(currentUser.user_metadata&&currentUser.user_metadata.name)||currentUser.email.split('@')[0];$('#email').textContent=currentUser.email;$('#authBox').hidden=true;$('#loggedBox').hidden=false;$('#rewardHub').hidden=false;await syncSaved();await loadRewards()}catch(_){}}
async function syncSaved(){if(!currentUser)return;try{const r=await req('/rest/v1/saved_contests?user_id=eq.'+encodeURIComponent(currentUser.id)+'&select=contest_id');if(r.ok){(await r.json()).forEach(x=>saved.add(String(x.contest_id)));localStorage.setItem('aich_saved',JSON.stringify([...saved]));render()}}catch(_){}}
async function signIn(){const email=$('#authEmail').value.trim(),password=$('#authPw').value,msg=$('#authMsg');if(!email||!password){msg.textContent='이메일과 비밀번호를 입력해 주세요.';return}msg.textContent='로그인 중...';try{const r=await req('/auth/v1/token?grant_type=password',{auth:false,method:'POST',body:JSON.stringify({email,password})});const d=await r.json();if(!r.ok){msg.textContent=d.msg||d.error_description||'로그인에 실패했습니다.';return}localStorage.setItem('aich_access_token',d.access_token);localStorage.setItem('aich_refresh_token',d.refresh_token||'');msg.textContent='로그인되었습니다.';await current()}catch(_){msg.textContent='서버 연결에 실패했습니다.'}}
async function signUp(){const name=$('#authName').value.trim(),email=$('#authEmail').value.trim(),password=$('#authPw').value,msg=$('#authMsg');if(!email||password.length<8){msg.textContent='이메일과 8자 이상 비밀번호를 입력해 주세요.';return}msg.textContent='회원가입 중...';try{const redirect=location.origin+'/';const r=await req('/auth/v1/signup?redirect_to='+encodeURIComponent(redirect),{auth:false,method:'POST',body:JSON.stringify({email,password,data:{name}})});const d=await r.json();if(!r.ok){msg.textContent=d.msg||d.error_description||'회원가입에 실패했습니다.';return}if(d.access_token){localStorage.setItem('aich_access_token',d.access_token);localStorage.setItem('aich_refresh_token',d.refresh_token||'');msg.textContent='가입 및 로그인되었습니다.';await current()}else msg.textContent='가입 확인 메일을 보냈습니다. 이메일 인증 후 로그인해 주세요.'}catch(_){msg.textContent='서버 연결에 실패했습니다.'}}
async function resetPassword(){const email=$('#authEmail').value.trim(),msg=$('#authMsg');if(!email){msg.textContent='먼저 가입한 이메일을 입력해 주세요.';return}msg.textContent='재설정 메일을 보내는 중...';try{const redirect=location.origin+'/?password_recovery=1';const r=await req('/auth/v1/recover?redirect_to='+encodeURIComponent(redirect),{auth:false,method:'POST',body:JSON.stringify({email})});msg.textContent=r.ok?'비밀번호 재설정 메일을 보냈습니다.':'재설정 메일 발송에 실패했습니다.'}catch(_){msg.textContent='서버 연결에 실패했습니다.'}}
function signOut(){localStorage.removeItem('aich_access_token');localStorage.removeItem('aich_refresh_token');location.reload()}
function kstDate(d=new Date()){return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Seoul',year:'numeric',month:'2-digit',day:'2-digit'}).format(d)}
function monthKey(){return kstDate().slice(0,7)}
function calcStreak(dateRows){const set=new Set(dateRows.map(x=>x.checkin_date));let cursor=new Date();const today=kstDate(cursor);if(!set.has(today))cursor=new Date(cursor.getTime()-86400000);let n=0;for(let i=0;i<365;i++){const k=kstDate(cursor);if(!set.has(k))break;n++;cursor=new Date(cursor.getTime()-86400000)}return n}
async function loadRewards(){if(!currentUser)return;try{const r=await req('/rest/v1/daily_checkins?user_id=eq.'+encodeURIComponent(currentUser.id)+'&select=checkin_date&order=checkin_date.desc&limit=400');const rows=r.ok?await r.json():[];const today=kstDate(),prefix=monthKey();monthCheckins=rows.filter(x=>String(x.checkin_date).startsWith(prefix)).length;const checked=rows.some(x=>x.checkin_date===today),streak=calcStreak(rows);$('#streakCount').textContent=`${streak}일 연속 출석`;$('#todayState').textContent=checked?'오늘 출석 완료 ✓':'오늘 출석 전';$('#checkinBtn').textContent=checked?'오늘 출석 완료 ✓':'오늘 출석 도장 찍기';$('#checkinBtn').classList.toggle('done',checked);$('#checkinBtn').disabled=checked;$('#monthCount').textContent=`${monthCheckins} / 20일`;$('#monthProgress').style.width=Math.min(100,(monthCheckins/20)*100)+'%';await loadCoffeeClaim();await loadAwardHistory()}catch(e){console.warn('reward load',e)}}
async function doCheckin(){if(!currentUser)return;const b=$('#checkinBtn');b.disabled=true;b.textContent='도장 찍는 중...';try{const r=await req('/rest/v1/daily_checkins',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({user_id:currentUser.id,checkin_date:kstDate()})});if(!r.ok&&r.status!==409)throw new Error('checkin '+r.status);await loadRewards()}catch(_){b.disabled=false;b.textContent='다시 시도하기'}}
async function loadCoffeeClaim(){if(!currentUser)return;const btn=$('#coffeeClaimBtn'),msg=$('#coffeeMsg'),ref=monthKey();let claimed=false;try{const r=await req('/rest/v1/reward_claims?user_id=eq.'+encodeURIComponent(currentUser.id)+'&reward_type=eq.monthly_coffee&source_ref=eq.'+encodeURIComponent(ref)+'&select=id,status&limit=1');if(r.ok){const rows=await r.json();claimed=rows.length>0;if(claimed)msg.textContent='☕ 이번 달 커피 리워드 신청이 접수되었습니다.'}}catch(_){}btn.disabled=claimed||monthCheckins<20;btn.textContent=claimed?'신청 완료':monthCheckins>=20?'커피 리워드 신청':'20일 출석 후 신청 가능'}
async function claimCoffee(){if(!currentUser||monthCheckins<20)return;const btn=$('#coffeeClaimBtn'),msg=$('#coffeeMsg');btn.disabled=true;msg.textContent='신청 중...';try{const r=await req('/rest/v1/reward_claims',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({user_id:currentUser.id,reward_type:'monthly_coffee',source_ref:monthKey()})});if(!r.ok)throw new Error();msg.textContent='☕ 신청 완료! 리워드 대상 여부는 운영 확인 후 안내됩니다.';btn.textContent='신청 완료'}catch(_){msg.textContent='신청 중 문제가 발생했습니다. 다시 시도해 주세요.';btn.disabled=false}}
function safeName(s){return String(s||'proof').replace(/[^a-zA-Z0-9._-]/g,'_').slice(-80)}
async function uploadProof(file){const path=`${currentUser.id}/${Date.now()}-${safeName(file.name)}`;const r=await fetch(`${API}/storage/v1/object/award-proofs/${encodeURI(path)}`,{method:'POST',headers:{'apikey':KEY,'Authorization':'Bearer '+token(),'Content-Type':file.type||'application/octet-stream','x-upsert':'false'},body:file});if(!r.ok)throw new Error('upload '+r.status);return path}
async function submitAward(){if(!currentUser)return;const title=$('#awardContest').value.trim(),award=$('#awardName').value.trim(),file=$('#awardProof').files[0],msg=$('#awardMsg'),btn=$('#awardSubmitBtn');if(!title||!award||!file){msg.textContent='공모전명, 수상명, 증빙 파일을 모두 입력해 주세요.';return}if(file.size>5*1024*1024){msg.textContent='증빙 파일은 5MB 이하로 업로드해 주세요.';return}btn.disabled=true;msg.textContent='증빙 파일 업로드 중...';try{const proof=await uploadProof(file);msg.textContent='수상 인증 접수 중...';const r=await req('/rest/v1/award_verifications',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({user_id:currentUser.id,contest_title:title,award_name:award,proof_url:proof})});if(!r.ok)throw new Error('insert '+r.status);$('#awardContest').value='';$('#awardName').value='';$('#awardProof').value='';msg.textContent='🏆 수상 인증이 접수되었습니다. 확인 후 상태가 업데이트됩니다.';await loadAwardHistory()}catch(e){msg.textContent='인증 제출 중 문제가 발생했습니다. 다시 시도해 주세요.';console.warn(e)}finally{btn.disabled=false}}
async function loadAwardHistory(){if(!currentUser)return;try{const r=await req('/rest/v1/award_verifications?user_id=eq.'+encodeURIComponent(currentUser.id)+'&select=id,contest_title,award_name,status,submitted_at&order=submitted_at.desc&limit=10');if(!r.ok)return;const rows=await r.json();$('#awardHistory').innerHTML=rows.length?rows.map(x=>`<div class="awardItem"><span class="awardStatus ${esc(x.status)}">${x.status==='approved'?'인증 완료':x.status==='rejected'?'반려':'검토 중'}</span><b>${esc(x.contest_title)}</b><small>🏆 ${esc(x.award_name)}</small></div>`).join(''):''}catch(_){}}
$$('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));
$('#searchTop').onclick=()=>go('explore');
$('#homeSearch').onclick=e=>{if(e.target.tagName!=='INPUT')go('explore')};
$('#homeQ').addEventListener('focus',()=>go('explore'));
$('#q').addEventListener('input',render);$('#aiFilter').addEventListener('change',render);$('#scopeFilter').addEventListener('change',render);
document.addEventListener('click',e=>{const b=e.target.closest('[data-cat]');if(b){activeCategory=b.dataset.cat;render()}});
$('[data-deadline]').onclick=()=>{go('explore');$('#q').value='';render()};
$('#detailClose').onclick=()=>$('#detailModal').classList.remove('open');$('#detailModal').onclick=e=>{if(e.target.id==='detailModal')e.currentTarget.classList.remove('open')};
$('#signInBtn').onclick=signIn;$('#signUpBtn').onclick=signUp;$('#resetBtn').onclick=resetPassword;$('#signOutBtn').onclick=signOut;
$('#checkinBtn').onclick=doCheckin;$('#coffeeClaimBtn').onclick=claimCoffee;$('#awardSubmitBtn').onclick=submitAward;
load();current();
})();